spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcoverdidev@gmail.com
    password: Password_123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
